version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - main-network
    env_file:
     - ./.env

volumes:
  db:
    driver: local

networks:
  main-network:


